In [1]:
import os
import sys

sys.path.append(os.path.join(".."))

In [2]:
import polars as pl

from generate.dataset.dataframe import DF
from generate.dataset.files import Files

In [3]:
target_folder = os.path.join("..", "data")
dataset_file = os.path.join(target_folder, "dataset.csv")

files_handler = Files(target_folder)
df = DF(dataset_file)

In [4]:
lazy_df = df.load_lazy_frame()
clean_df = DF.clean_duplicated_rows(lazy_df)
cdf = clean_df.collect()
len(cdf)

5456

In [5]:
duplicated_files = DF.get_files_via_left_join(lazy_df, clean_df)
len(duplicated_files)

30184

In [15]:
assert len(lazy_df.collect()) - len(duplicated_files) == len(clean_df.collect())

---

In [6]:
lazy_df.filter(pl.col("file") == duplicated_files[0]).collect()

shape: (1, 14)
┌───────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ depth ┆ file        ┆ result     ┆ … ┆ n_one_qubi ┆ amount_gat ┆ file_size_ ┆ n_barriers │
│ ---   ┆ ---   ┆ ---         ┆ ---        ┆   ┆ t_gates    ┆ es         ┆ bytes      ┆ ---        │
│ u32   ┆ u8    ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u8         │
│       ┆       ┆             ┆            ┆   ┆ u8         ┆ str        ┆ u32        ┆            │
╞═══════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 744   ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/744.png  ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
└───────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [7]:
lazy_df.filter(pl.col("file") == duplicated_files[0]).collect().select("hash").item()

'fda63577ebb4ac157d0a844507e94f66'

In [8]:
lazy_df.filter(pl.col("hash") == "fda63577ebb4ac157d0a844507e94f66").collect()

shape: (18, 14)
┌───────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ depth ┆ file        ┆ result     ┆ … ┆ n_one_qubi ┆ amount_gat ┆ file_size_ ┆ n_barriers │
│ ---   ┆ ---   ┆ ---         ┆ ---        ┆   ┆ t_gates    ┆ es         ┆ bytes      ┆ ---        │
│ u32   ┆ u8    ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u8         │
│       ┆       ┆             ┆            ┆   ┆ u8         ┆ str        ┆ u32        ┆            │
╞═══════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 248   ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/248.png  ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 744   ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/744.png  ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 1457  ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/1457.png ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 2635  ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/2635.png ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 3410  ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/3410.png ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ …     ┆ …     ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 22351 ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/22351.pn ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 23033 ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/23033.pn ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 27156 ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/27156.pn ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 31000 ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/31000.pn ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
│ 32736 ┆ 7     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 4          ┆ {"swap":   ┆ 18044      ┆ 3          │
│       ┆       ┆ es/32736.pn ┆ 0.0, 0.0,  ┆   ┆            ┆ 2, "h": 1, ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆ "cz": 3,   ┆            ┆            │
│       ┆       ┆             ┆            ┆   ┆            ┆ "…         ┆            ┆            │
└───────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘