In [1]:
import os
import sys

sys.path.append(os.path.join(".."))

In [2]:
import polars as pl

from generate.dataset.dataframe import DF
from generate.dataset.files import Files

In [3]:
target_folder = os.path.join("..", "data")
dataset_file = os.path.join(target_folder, "dataset.csv")

files_handler = Files(target_folder)
df = DF(dataset_file)

In [4]:
lazy_df = df.load_lazy_frame()
clean_df = DF.clean_duplicated_rows(lazy_df)
cdf = clean_df.collect()
len(cdf)

60233

In [5]:
duplicated_files = DF.get_files_via_left_join(lazy_df, clean_df)
len(duplicated_files)

527

In [6]:
assert len(lazy_df.collect()) - len(duplicated_files) == len(clean_df.collect())

---

In [7]:
lazy_df.filter(pl.col("file") == duplicated_files[0]).collect()

shape: (1, 14)
┌───────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ depth ┆ file        ┆ result     ┆ … ┆ n_one_qubi ┆ amount_gat ┆ file_size_ ┆ n_barriers │
│ ---   ┆ ---   ┆ ---         ┆ ---        ┆   ┆ t_gates    ┆ es         ┆ bytes      ┆ ---        │
│ u32   ┆ u8    ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u8         │
│       ┆       ┆             ┆            ┆   ┆ u8         ┆ str        ┆ u32        ┆            │
╞═══════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 19096 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 1          ┆ {"h": 1}   ┆ 6315       ┆ 0          │
│       ┆       ┆ es/19096.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
└───────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [9]:
hash_ = lazy_df.filter(pl.col("file") == duplicated_files[0]).collect().select("hash").item()
hash_

'907034a11b78ae00e5481abf187bb027'

In [10]:
lazy_df.filter(pl.col("hash") == hash_).collect()

shape: (4, 14)
┌───────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ depth ┆ file        ┆ result     ┆ … ┆ n_one_qubi ┆ amount_gat ┆ file_size_ ┆ n_barriers │
│ ---   ┆ ---   ┆ ---         ┆ ---        ┆   ┆ t_gates    ┆ es         ┆ bytes      ┆ ---        │
│ u32   ┆ u8    ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u8         │
│       ┆       ┆             ┆            ┆   ┆ u8         ┆ str        ┆ u32        ┆            │
╞═══════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 13547 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 1          ┆ {"h": 1}   ┆ 6315       ┆ 0          │
│       ┆       ┆ es/13547.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 19096 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 1          ┆ {"h": 1}   ┆ 6315       ┆ 0          │
│       ┆       ┆ es/19096.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 20584 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 1          ┆ {"h": 1}   ┆ 6315       ┆ 0          │
│       ┆       ┆ es/20584.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 38719 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 1          ┆ {"h": 1}   ┆ 6315       ┆ 0          │
│       ┆       ┆ es/38719.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
└───────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘