In [2]:
import os
import sys

sys.path.append(os.path.join(".."))

In [20]:
import polars as pl

from generate.dataset.dataframe import DF
from generate.dataset.files import Files

In [5]:
target_folder = os.path.join("..", "data")
dataset_file = os.path.join(target_folder, "dataset.csv")

files_handler = Files(target_folder)
df = DF(dataset_file)

In [9]:
lazy_df = df.load_lazy_frame()
clean_df = DF.clean_duplicated_rows(lazy_df)
len(clean_df.collect())

620

In [11]:
duplicated_files = DF.get_files_via_left_join(lazy_df, clean_df)
len(duplicated_files)

59520

In [15]:
assert len(lazy_df.collect()) - len(duplicated_files) == len(clean_df.collect())

---

In [22]:
lazy_df.filter(pl.col("file") == duplicated_files[0]).collect()

shape: (1, 14)
┌───────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ depth ┆ file        ┆ result     ┆ … ┆ n_one_qubi ┆ amount_gat ┆ file_size_ ┆ n_barriers │
│ ---   ┆ ---   ┆ ---         ┆ ---        ┆   ┆ t_gates    ┆ es         ┆ bytes      ┆ ---        │
│ u32   ┆ u8    ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u8         │
│       ┆       ┆             ┆            ┆   ┆ u8         ┆ str        ┆ u32        ┆            │
╞═══════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/0.png    ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
└───────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [26]:
lazy_df.filter(pl.col("file") == duplicated_files[0]).collect().select("hash").item()

'5daa01ac9e6f129f8b72b75c87cdb1f3'

In [27]:
lazy_df.filter(pl.col("hash") == "5daa01ac9e6f129f8b72b75c87cdb1f3").collect()

shape: (117, 14)
┌───────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ depth ┆ file        ┆ result     ┆ … ┆ n_one_qubi ┆ amount_gat ┆ file_size_ ┆ n_barriers │
│ ---   ┆ ---   ┆ ---         ┆ ---        ┆   ┆ t_gates    ┆ es         ┆ bytes      ┆ ---        │
│ u32   ┆ u8    ┆ str         ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u8         │
│       ┆       ┆             ┆            ┆   ┆ u8         ┆ str        ┆ u32        ┆            │
╞═══════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 31    ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/31.png   ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 0     ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/0.png    ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 279   ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/279.png  ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 2759  ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/2759.png ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 2976  ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/2976.png ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆             ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ …     ┆ …     ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 60047 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/60047.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 60295 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/60295.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 60419 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/60419.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 60481 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/60481.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
│ 60357 ┆ 1     ┆ ./data/imag ┆ [1.0, 0.0, ┆ … ┆ 0          ┆ {}         ┆ 4652       ┆ 0          │
│       ┆       ┆ es/60357.pn ┆ 0.0, 0.0,  ┆   ┆            ┆            ┆            ┆            │
│       ┆       ┆ g           ┆ 0.0, 0.0,… ┆   ┆            ┆            ┆            ┆            │
└───────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘